language: php

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm
    allow_failures:
        - php: hhvm

before_install:
    - composer self-update
    - curl -LSs https://box-project.github.io/box2/installer.php | php
    - mv box.phar box
    - chmod 755 box

install:
    - composer install

script:
    - phpunit
    - php box build
    - sha1sum pskeleton.phar > pskeleton.sha1

deploy:
    provider: releases
    api_key: $GITHUB_API_TOKEN
    file:
        - pskeleton.phar
        - pskeleton.sha1
    skip_cleanup: true
    on:
        tags: true
        php: '5.6'
